site_name: Documentación Tarea 1 RA 1

nav:
  - Home: index.md
  - Código-comentado: codigo_comentado.md
  - Ejecución-y-depuración: ejecucion_debug.md
  - Tests: tests.md
  - Sandbox: sandbox.md
  - Reflexión: reflexion.md

doc_dir: docs



